apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
