apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app-container
    image: alyssa7/proj3:proj3_app
    ports:
    - containerPort: 5000
